MyCalendarApp/MyCalendarApp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from MyCalendarApp import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('mycalendar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyCalendarApp/account/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import loginView, registerView, logoutView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', loginView, name="login"),
    path('register', registerView, name="register"),
    path('logout', logoutView, name="logout"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('account/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('account/password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('account/password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('account/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('account/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('account/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

MyCalendarApp/account/models.py
import hashlib
import os

from PIL import Image
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver

from MyCalendarApp import settings


def upload_location(instance,filename,**kwargs):
    file_path = 'profile_images/{filename}'.format(filename=hashlib.md5(str(instance.email).encode()).hexdigest() + os.path.splitext(filename)[1]
    )
    return file_path

class MyAccountManager(BaseUserManager):

    def create_user(self, email, nick_name, password, profile_img=None):
        user = self.model(email=email, nick_name=nick_name, profile_img=profile_img)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nick_name, password, profile_img=None):
        user = self.create_user(email, nick_name, password, profile_img)
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user



class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="E-Mail", max_length=60, unique=True)
    nick_name = models.CharField(verbose_name="Nickname", max_length=20)
    profile_img = models.ImageField(upload_to=upload_location, null=True, blank=True)

    # necessary
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    # to use email as a login field
    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ["nick_name"]

    objects = MyAccountManager()

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True



@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def post_save_compress_img(sender, instance, *args, **kwargs):
    if instance.profile_img:
        picture = Image.open(instance.profile_img.path)
        picture.save(instance.profile_img.path, optimize=True, quality=30)

MyCalendarApp/account/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from account.models import Account


class RegistrationForm(UserCreationForm):

    class Meta:
        model = Account
        fields = ("email", "nick_name", "password1", "password2")

class AccountAuthenticationForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']

            if not authenticate(email=email, password=password):
                self.add_error("password", "E-Mail ili lozinka su pogrešni.")
                raise forms.ValidationError("E-Mail ili lozinka su pogrešni.")

MyCalendarApp/account/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from account.forms import AccountAuthenticationForm, RegistrationForm


# Create your views here

def loginView(request):
    context = {}
    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']

            user = authenticate(email=email,password=password)
            login(request,user)
            return redirect('home')
    else:
        form = AccountAuthenticationForm()
    context['form'] = form
    return render(request, "login.html", context)


def logoutView(request):
    logout(request)
    return redirect("login")


def registerView(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = RegistrationForm()
    context['form'] = form
    return render(request, "register.html", context)

MyCalendarApp/account/templates/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container-fluid">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h1 class="login-heading mb-4">Moj kalendar</h1>
                <h3 class="login-heading mb-4">Dobrodošli nazad</h3>
              <form method="post">{% csrf_token %}
                <div class="form-label-group">
                  {% render_field form.email class="form-control" %}
                  <label for="id_email">E-Mail adresa</label>
                    {{ form.email.errors }}
                </div>
                <div class="form-label-group">
                  {% render_field form.password class="form-control" type="password" %}
                  <label for="id_password">Lozinka</label>
                    {{ form.password.errors }}
                </div>
                <button class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Prijavite se</button>
                  <a href="{% url 'register' %}" class="btn btn-outline-primary btn-block btn-login text-uppercase font-weight-bold mb-2">Registracija</a>
                <div class="text-center">
                  <a class="small" href="{% url 'password_reset' %}">Zaboravio/la si lozinku?</a></div>
              </form>
                <p style="margin-top: 128px;">
                <small>
                    Photo by <a href="https://unsplash.com/@maddibazzocco">Maddi Bazzocco</a> on <a href="https://unsplash.com/s/photos/calendar-2023">Unsplash</a>
                </small>
                </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

MyCalendarApp/account/templates/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container-fluid">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h1 class="login-heading mb-4">Moj kalendar</h1>
                <h3 class="login-heading mb-4">Registracija</h3>
              <form method="post"> {% csrf_token %}
                <div class="form-label-group">
                  {% render_field form.email class="form-control" %}
                  <label for="id_email">E-Mail adresa</label>
                  {{ form.email.errors }}
                </div>
                <div class="form-label-group">
                  {% render_field form.nick_name class="form-control" %}
                  <label for="id_nick_name">Korisničko ime</label>
                  {{ form.nick_name.errors }}
                </div>

                <div class="form-label-group">
                  {% render_field form.password1 class="form-control" %}
                  <label for="id_password1">Lozinka</label>
                  {{ form.password1.errors }}
                </div>
                  <div class="form-label-group">
                  {% render_field form.password2 class="form-control" %}
                  <label for="id_password2">Potvrdite lozinku</label>
                  {{ form.password2.errors }}
                </div>
                <button class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Registracija</button>
              </form>
                <p style="margin-top: 128px;">
                <small>
                    Photo by <a href="https://unsplash.com/@maddibazzocco">Maddi Bazzocco</a> on <a href="https://unsplash.com/s/photos/calendar-2023">Unsplash</a>
                </small>
                </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}